import "./DoxygenInfo.scss";
import React from "react";

export default class DoxygenInfo extends React.Component
{
   render()
   {
      let version = this.props.version;
      return <div className="doxygen-info">generated by Doxygen: {version}</div>;
   }
};